services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    restart: unless-stopped

  app:
    build: .
    container_name: doc-intel
    environment:
      - OLLAMA_URL=http://ollama:11434/api/generate
    volumes:
      - .:/app
    command: ["sh", "-c", "sleep 10 && python ollama_integration.py"]
    restart: no

volumes:
  ollama-data:
